entities:
- file:
    path: /home/students/q.abbas/Protein_design_hack/FGFR_binder_hackathon/FGFR2_1DJS_chainA_clean.pdb
    include:
    - chain:
        id: A
    not_design:
    - chain:
        id: A
    binding_types:
    - chain:
        id: A
        binding: 23,131,133,138,158
- protein:
    id: X
    sequence: 30..55
    msa: empty
